export const LOAD_BOOKS = "BOOKS/LOAD_BOOKS";
export const DELETE_BOOK = "BOOKS/DELETE_BOOK";
export const SET_ACTIVE_BOOK = "BOOKS/SET_ACTIVE_BOOK";
export const ADD_NEW_BOOK = "BOOKS/ADD_NEW_BOOK";
export const SHOW_BOOK_MESSAGE = "BOOKS/SHOW_BOOK_MESSAGE";
export const HIDE_BOOK_MESSAGE = "BOOKS/HIDE_BOOK_MESSAGE";